package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Acudiente generated by hbm2java
 */
@Entity
@Table(name = "acudiente", catalog = "bd_sianglv")
public class Acudiente implements java.io.Serializable {

	
	private static final long serialVersionUID = -5455182634945739683L;
	
	
	private Integer acuId;
	private Persona persona;
	private Parentesco parentesco;
	private Estudiantes estudiantes;
	private boolean acuResponsable;
	private Set<Matricula> matriculas = new HashSet<Matricula>(0);

	public Acudiente() {
	}

	public Acudiente(Persona persona, Parentesco parentesco,
			Estudiantes estudiantes, boolean acuResponsable) {
		this.persona = persona;
		this.parentesco = parentesco;
		this.estudiantes = estudiantes;
		this.acuResponsable = acuResponsable;
	}

	public Acudiente(Persona persona, Parentesco parentesco,
			Estudiantes estudiantes, boolean acuResponsable,
			Set<Matricula> matriculas) {
		this.persona = persona;
		this.parentesco = parentesco;
		this.estudiantes = estudiantes;
		this.acuResponsable = acuResponsable;
		this.matriculas = matriculas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "acu_id", unique = true, nullable = false)
	public Integer getAcuId() {
		return this.acuId;
	}

	public void setAcuId(Integer acuId) {
		this.acuId = acuId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "per_id", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "parent_id", nullable = false)
	public Parentesco getParentesco() {
		return this.parentesco;
	}

	public void setParentesco(Parentesco parentesco) {
		this.parentesco = parentesco;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "est_id", nullable = false)
	public Estudiantes getEstudiantes() {
		return this.estudiantes;
	}

	public void setEstudiantes(Estudiantes estudiantes) {
		this.estudiantes = estudiantes;
	}

	@Column(name = "acu_responsable", nullable = false)
	public boolean isAcuResponsable() {
		return this.acuResponsable;
	}

	public void setAcuResponsable(boolean acuResponsable) {
		this.acuResponsable = acuResponsable;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "acudiente")
	public Set<Matricula> getMatriculas() {
		return this.matriculas;
	}

	public void setMatriculas(Set<Matricula> matriculas) {
		this.matriculas = matriculas;
	}

}
