package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * AnioLectivo generated by hbm2java
 */
@Entity
@Table(name = "anio_lectivo", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "ale_anio"))
public class AnioLectivo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8622591631662794091L;
	private Integer aleId;
	private int aleAnio;
	private Integer aleNumeroPeriodos;
	private Set<CargaAcademica> cargaAcademicas = new HashSet<CargaAcademica>(0);
	private Set<DirectorGrupo> directorGrupos = new HashSet<DirectorGrupo>(0);
	private Set<Matricula> matriculas = new HashSet<Matricula>(0);

	public AnioLectivo() {
	}

	public AnioLectivo(int aleAnio) {
		this.aleAnio = aleAnio;
	}

	public AnioLectivo(int aleAnio, Integer aleNumeroPeriodos,
			Set<CargaAcademica> cargaAcademicas,
			Set<DirectorGrupo> directorGrupos, Set<Matricula> matriculas) {
		this.aleAnio = aleAnio;
		this.aleNumeroPeriodos = aleNumeroPeriodos;
		this.cargaAcademicas = cargaAcademicas;
		this.directorGrupos = directorGrupos;
		this.matriculas = matriculas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ale_id", unique = true, nullable = false)
	public Integer getAleId() {
		return this.aleId;
	}

	public void setAleId(Integer aleId) {
		this.aleId = aleId;
	}

	@Column(name = "ale_anio", unique = true, nullable = false)
	public int getAleAnio() {
		return this.aleAnio;
	}

	public void setAleAnio(int aleAnio) {
		this.aleAnio = aleAnio;
	}

	@Column(name = "ale_numero_periodos")
	public Integer getAleNumeroPeriodos() {
		return this.aleNumeroPeriodos;
	}

	public void setAleNumeroPeriodos(Integer aleNumeroPeriodos) {
		this.aleNumeroPeriodos = aleNumeroPeriodos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "anioLectivo")
	public Set<CargaAcademica> getCargaAcademicas() {
		return this.cargaAcademicas;
	}

	public void setCargaAcademicas(Set<CargaAcademica> cargaAcademicas) {
		this.cargaAcademicas = cargaAcademicas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "anioLectivo")
	public Set<DirectorGrupo> getDirectorGrupos() {
		return this.directorGrupos;
	}

	public void setDirectorGrupos(Set<DirectorGrupo> directorGrupos) {
		this.directorGrupos = directorGrupos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "anioLectivo")
	public Set<Matricula> getMatriculas() {
		return this.matriculas;
	}

	public void setMatriculas(Set<Matricula> matriculas) {
		this.matriculas = matriculas;
	}

}
