package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Area generated by hbm2java
 */
@Entity
@Table(name = "area", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "are_area"))
public class Area implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5769521382148757403L;
	private Integer areId;
	private String areArea;
	private Set<Materias> materiases = new HashSet<Materias>(0);

	public Area() {
	}

	public Area(String areArea) {
		this.areArea = areArea;
	}

	public Area(String areArea, Set<Materias> materiases) {
		this.areArea = areArea;
		this.materiases = materiases;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "are_id", unique = true, nullable = false)
	public Integer getAreId() {
		return this.areId;
	}

	public void setAreId(Integer areId) {
		this.areId = areId;
	}

	@Column(name = "are_area", unique = true, nullable = false, length = 50)
	public String getAreArea() {
		return this.areArea;
	}

	public void setAreArea(String areArea) {
		this.areArea = areArea;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "area")
	public Set<Materias> getMateriases() {
		return this.materiases;
	}

	public void setMateriases(Set<Materias> materiases) {
		this.materiases = materiases;
	}

}
