package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Calendario generated by hbm2java
 */
@Entity
@Table(name = "calendario", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "cal_nombre"))
public class Calendario implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2291654355563836400L;
	private Integer calId;
	private String calNombre;
	private Set<Establecimiento> establecimientos = new HashSet<Establecimiento>(
			0);

	public Calendario() {
	}

	public Calendario(String calNombre) {
		this.calNombre = calNombre;
	}

	public Calendario(String calNombre, Set<Establecimiento> establecimientos) {
		this.calNombre = calNombre;
		this.establecimientos = establecimientos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cal_id", unique = true, nullable = false)
	public Integer getCalId() {
		return this.calId;
	}

	public void setCalId(Integer calId) {
		this.calId = calId;
	}

	@Column(name = "cal_nombre", unique = true, nullable = false, length = 10)
	public String getCalNombre() {
		return this.calNombre;
	}

	public void setCalNombre(String calNombre) {
		this.calNombre = calNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "calendario")
	public Set<Establecimiento> getEstablecimientos() {
		return this.establecimientos;
	}

	public void setEstablecimientos(Set<Establecimiento> establecimientos) {
		this.establecimientos = establecimientos;
	}

}
