package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Capacidades generated by hbm2java
 */
@Entity
@Table(name = "capacidades", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "cap_nombre"))
public class Capacidades implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8996884414292033676L;
	private Integer capId;
	private String capNombre;
	private Set<Estudiantes> estudianteses = new HashSet<Estudiantes>(0);

	public Capacidades() {
	}

	public Capacidades(String capNombre) {
		this.capNombre = capNombre;
	}

	public Capacidades(String capNombre, Set<Estudiantes> estudianteses) {
		this.capNombre = capNombre;
		this.estudianteses = estudianteses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "cap_id", unique = true, nullable = false)
	public Integer getCapId() {
		return this.capId;
	}

	public void setCapId(Integer capId) {
		this.capId = capId;
	}

	@Column(name = "cap_nombre", unique = true, nullable = false, length = 100)
	public String getCapNombre() {
		return this.capNombre;
	}

	public void setCapNombre(String capNombre) {
		this.capNombre = capNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "capacidades")
	public Set<Estudiantes> getEstudianteses() {
		return this.estudianteses;
	}

	public void setEstudianteses(Set<Estudiantes> estudianteses) {
		this.estudianteses = estudianteses;
	}

}
