package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * ConfigSede generated by hbm2java
 */
@Entity
@Table(name = "config_sede", catalog = "bd_sianglv")
public class ConfigSede implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 296641684255635215L;
	private Integer confId;
	private NivelEscolaridad nivelEscolaridad;
	private Sede sede;
	private Jornada jornada;
	private Set<UbicacionCurso> ubicacionCursos = new HashSet<UbicacionCurso>(0);

	public ConfigSede() {
	}

	public ConfigSede(NivelEscolaridad nivelEscolaridad, Sede sede,
			Jornada jornada) {
		this.nivelEscolaridad = nivelEscolaridad;
		this.sede = sede;
		this.jornada = jornada;
	}

	public ConfigSede(NivelEscolaridad nivelEscolaridad, Sede sede,
			Jornada jornada, Set<UbicacionCurso> ubicacionCursos) {
		this.nivelEscolaridad = nivelEscolaridad;
		this.sede = sede;
		this.jornada = jornada;
		this.ubicacionCursos = ubicacionCursos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "conf_id", unique = true, nullable = false)
	public Integer getConfId() {
		return this.confId;
	}

	public void setConfId(Integer confId) {
		this.confId = confId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "nies_id", nullable = false)
	public NivelEscolaridad getNivelEscolaridad() {
		return this.nivelEscolaridad;
	}

	public void setNivelEscolaridad(NivelEscolaridad nivelEscolaridad) {
		this.nivelEscolaridad = nivelEscolaridad;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sed_id", nullable = false)
	public Sede getSede() {
		return this.sede;
	}

	public void setSede(Sede sede) {
		this.sede = sede;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "jor_id", nullable = false)
	public Jornada getJornada() {
		return this.jornada;
	}

	public void setJornada(Jornada jornada) {
		this.jornada = jornada;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "configSede")
	public Set<UbicacionCurso> getUbicacionCursos() {
		return this.ubicacionCursos;
	}

	public void setUbicacionCursos(Set<UbicacionCurso> ubicacionCursos) {
		this.ubicacionCursos = ubicacionCursos;
	}

}
