package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Departamento generated by hbm2java
 */
@Entity
@Table(name = "departamento", catalog = "bd_sianglv")
public class Departamento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1333014315588760591L;
	private int depCodigo;
	private Pais pais;
	private String depDepartamento;
	private Set<Municipio> municipios = new HashSet<Municipio>(0);

	public Departamento() {
	}

	public Departamento(int depCodigo, Pais pais, String depDepartamento) {
		this.depCodigo = depCodigo;
		this.pais = pais;
		this.depDepartamento = depDepartamento;
	}

	public Departamento(int depCodigo, Pais pais, String depDepartamento,
			Set<Municipio> municipios) {
		this.depCodigo = depCodigo;
		this.pais = pais;
		this.depDepartamento = depDepartamento;
		this.municipios = municipios;
	}

	@Id
	@Column(name = "dep_codigo", unique = true, nullable = false)
	public int getDepCodigo() {
		return this.depCodigo;
	}

	public void setDepCodigo(int depCodigo) {
		this.depCodigo = depCodigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pais_id", nullable = false)
	public Pais getPais() {
		return this.pais;
	}

	public void setPais(Pais pais) {
		this.pais = pais;
	}

	@Column(name = "dep_departamento", nullable = false, length = 50)
	public String getDepDepartamento() {
		return this.depDepartamento;
	}

	public void setDepDepartamento(String depDepartamento) {
		this.depDepartamento = depDepartamento;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "departamento")
	public Set<Municipio> getMunicipios() {
		return this.municipios;
	}

	public void setMunicipios(Set<Municipio> municipios) {
		this.municipios = municipios;
	}

}
