package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Discapacidades generated by hbm2java
 */
@Entity
@Table(name = "discapacidades", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "disc_nombre"))
public class Discapacidades implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3263762987431463924L;
	private Integer discId;
	private String discNombre;
	private boolean discTipo;
	private Set<Establecimiento> establecimientos = new HashSet<Establecimiento>(
			0);
	private Set<Estudiantes> estudianteses = new HashSet<Estudiantes>(0);

	public Discapacidades() {
	}

	public Discapacidades(String discNombre, boolean discTipo) {
		this.discNombre = discNombre;
		this.discTipo = discTipo;
	}

	public Discapacidades(String discNombre, boolean discTipo,
			Set<Establecimiento> establecimientos,
			Set<Estudiantes> estudianteses) {
		this.discNombre = discNombre;
		this.discTipo = discTipo;
		this.establecimientos = establecimientos;
		this.estudianteses = estudianteses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "disc_id", unique = true, nullable = false)
	public Integer getDiscId() {
		return this.discId;
	}

	public void setDiscId(Integer discId) {
		this.discId = discId;
	}

	@Column(name = "disc_nombre", unique = true, nullable = false, length = 100)
	public String getDiscNombre() {
		return this.discNombre;
	}

	public void setDiscNombre(String discNombre) {
		this.discNombre = discNombre;
	}

	@Column(name = "disc_tipo", nullable = false)
	public boolean isDiscTipo() {
		return this.discTipo;
	}

	public void setDiscTipo(boolean discTipo) {
		this.discTipo = discTipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discapacidades")
	public Set<Establecimiento> getEstablecimientos() {
		return this.establecimientos;
	}

	public void setEstablecimientos(Set<Establecimiento> establecimientos) {
		this.establecimientos = establecimientos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "discapacidades")
	public Set<Estudiantes> getEstudianteses() {
		return this.estudianteses;
	}

	public void setEstudianteses(Set<Estudiantes> estudianteses) {
		this.estudianteses = estudianteses;
	}

}
