package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Domicilio generated by hbm2java
 */
@Entity
@Table(name = "domicilio", catalog = "bd_sianglv")
public class Domicilio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1548788835051764643L;
	private Integer domId;
	private Municipio municipio;
	private String domDireccion;
	private String domTelefono;
	private String domCelular;
	private Set<Persona> personas = new HashSet<Persona>(0);

	public Domicilio() {
	}

	public Domicilio(Municipio municipio, String domDireccion) {
		this.municipio = municipio;
		this.domDireccion = domDireccion;
	}

	public Domicilio(Municipio municipio, String domDireccion,
			String domTelefono, String domCelular, Set<Persona> personas) {
		this.municipio = municipio;
		this.domDireccion = domDireccion;
		this.domTelefono = domTelefono;
		this.domCelular = domCelular;
		this.personas = personas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "dom_id", unique = true, nullable = false)
	public Integer getDomId() {
		return this.domId;
	}

	public void setDomId(Integer domId) {
		this.domId = domId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mun_id", nullable = false)
	public Municipio getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(Municipio municipio) {
		this.municipio = municipio;
	}

	@Column(name = "dom_direccion", nullable = false, length = 50)
	public String getDomDireccion() {
		return this.domDireccion;
	}

	public void setDomDireccion(String domDireccion) {
		this.domDireccion = domDireccion;
	}

	@Column(name = "dom_telefono", length = 20)
	public String getDomTelefono() {
		return this.domTelefono;
	}

	public void setDomTelefono(String domTelefono) {
		this.domTelefono = domTelefono;
	}

	@Column(name = "dom_celular", length = 20)
	public String getDomCelular() {
		return this.domCelular;
	}

	public void setDomCelular(String domCelular) {
		this.domCelular = domCelular;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "domicilio")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

}
