package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Establecimiento generated by hbm2java
 */
@Entity
@Table(name = "establecimiento", catalog = "bd_sianglv")
public class Establecimiento implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5705358531783435128L;
	private Integer estaId;
	private Calendario calendario;
	private Genero genero;
	private Persona personaByIdRector;
	private Discapacidades discapacidades;
	private NovedadInstitucion novedadInstitucion;
	private Persona personaByIdSecretario;
	private PropiedadJuridica propiedadJuridica;
	private String estaNombre;
	private String estaNit;
	private String estaResolucion;
	private String estaTelefono;
	private String estaFax;
	private String estaWeb;
	private String estaCorreo;
	private Integer estaNumeroSedes;
	private String estaNucleoEducativo;
	private String estaDireccionOficinaNucleo;
	private Boolean estaSubsidio;
	private String estaCapacidades;
	private Set<Sede> sedes = new HashSet<Sede>(0);

	public Establecimiento() {
	}

	public Establecimiento(Calendario calendario, Genero genero,
			Persona personaByIdRector, Persona personaByIdSecretario,
			String estaNombre, String estaNit, String estaResolucion) {
		this.calendario = calendario;
		this.genero = genero;
		this.personaByIdRector = personaByIdRector;
		this.personaByIdSecretario = personaByIdSecretario;
		this.estaNombre = estaNombre;
		this.estaNit = estaNit;
		this.estaResolucion = estaResolucion;
	}

	public Establecimiento(Calendario calendario, Genero genero,
			Persona personaByIdRector, Discapacidades discapacidades,
			NovedadInstitucion novedadInstitucion,
			Persona personaByIdSecretario, PropiedadJuridica propiedadJuridica,
			String estaNombre, String estaNit, String estaResolucion,
			String estaTelefono, String estaFax, String estaWeb,
			String estaCorreo, Integer estaNumeroSedes,
			String estaNucleoEducativo, String estaDireccionOficinaNucleo,
			Boolean estaSubsidio, String estaCapacidades, Set<Sede> sedes) {
		this.calendario = calendario;
		this.genero = genero;
		this.personaByIdRector = personaByIdRector;
		this.discapacidades = discapacidades;
		this.novedadInstitucion = novedadInstitucion;
		this.personaByIdSecretario = personaByIdSecretario;
		this.propiedadJuridica = propiedadJuridica;
		this.estaNombre = estaNombre;
		this.estaNit = estaNit;
		this.estaResolucion = estaResolucion;
		this.estaTelefono = estaTelefono;
		this.estaFax = estaFax;
		this.estaWeb = estaWeb;
		this.estaCorreo = estaCorreo;
		this.estaNumeroSedes = estaNumeroSedes;
		this.estaNucleoEducativo = estaNucleoEducativo;
		this.estaDireccionOficinaNucleo = estaDireccionOficinaNucleo;
		this.estaSubsidio = estaSubsidio;
		this.estaCapacidades = estaCapacidades;
		this.sedes = sedes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "esta_id", unique = true, nullable = false)
	public Integer getEstaId() {
		return this.estaId;
	}

	public void setEstaId(Integer estaId) {
		this.estaId = estaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "cal_id", nullable = false)
	public Calendario getCalendario() {
		return this.calendario;
	}

	public void setCalendario(Calendario calendario) {
		this.calendario = calendario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "genero_id", nullable = false)
	public Genero getGenero() {
		return this.genero;
	}

	public void setGenero(Genero genero) {
		this.genero = genero;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_rector", nullable = false)
	public Persona getPersonaByIdRector() {
		return this.personaByIdRector;
	}

	public void setPersonaByIdRector(Persona personaByIdRector) {
		this.personaByIdRector = personaByIdRector;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "disc_id")
	public Discapacidades getDiscapacidades() {
		return this.discapacidades;
	}

	public void setDiscapacidades(Discapacidades discapacidades) {
		this.discapacidades = discapacidades;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "noin_id")
	public NovedadInstitucion getNovedadInstitucion() {
		return this.novedadInstitucion;
	}

	public void setNovedadInstitucion(NovedadInstitucion novedadInstitucion) {
		this.novedadInstitucion = novedadInstitucion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_secretario", nullable = false)
	public Persona getPersonaByIdSecretario() {
		return this.personaByIdSecretario;
	}

	public void setPersonaByIdSecretario(Persona personaByIdSecretario) {
		this.personaByIdSecretario = personaByIdSecretario;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "proju_id")
	public PropiedadJuridica getPropiedadJuridica() {
		return this.propiedadJuridica;
	}

	public void setPropiedadJuridica(PropiedadJuridica propiedadJuridica) {
		this.propiedadJuridica = propiedadJuridica;
	}

	@Column(name = "esta_nombre", nullable = false, length = 300)
	public String getEstaNombre() {
		return this.estaNombre;
	}

	public void setEstaNombre(String estaNombre) {
		this.estaNombre = estaNombre;
	}

	@Column(name = "esta_nit", nullable = false, length = 30)
	public String getEstaNit() {
		return this.estaNit;
	}

	public void setEstaNit(String estaNit) {
		this.estaNit = estaNit;
	}

	@Column(name = "esta_resolucion", nullable = false, length = 50)
	public String getEstaResolucion() {
		return this.estaResolucion;
	}

	public void setEstaResolucion(String estaResolucion) {
		this.estaResolucion = estaResolucion;
	}

	@Column(name = "esta_telefono", length = 20)
	public String getEstaTelefono() {
		return this.estaTelefono;
	}

	public void setEstaTelefono(String estaTelefono) {
		this.estaTelefono = estaTelefono;
	}

	@Column(name = "esta_fax", length = 20)
	public String getEstaFax() {
		return this.estaFax;
	}

	public void setEstaFax(String estaFax) {
		this.estaFax = estaFax;
	}

	@Column(name = "esta_web", length = 50)
	public String getEstaWeb() {
		return this.estaWeb;
	}

	public void setEstaWeb(String estaWeb) {
		this.estaWeb = estaWeb;
	}

	@Column(name = "esta_correo", length = 50)
	public String getEstaCorreo() {
		return this.estaCorreo;
	}

	public void setEstaCorreo(String estaCorreo) {
		this.estaCorreo = estaCorreo;
	}

	@Column(name = "esta_numero_sedes")
	public Integer getEstaNumeroSedes() {
		return this.estaNumeroSedes;
	}

	public void setEstaNumeroSedes(Integer estaNumeroSedes) {
		this.estaNumeroSedes = estaNumeroSedes;
	}

	@Column(name = "esta_nucleo_educativo", length = 20)
	public String getEstaNucleoEducativo() {
		return this.estaNucleoEducativo;
	}

	public void setEstaNucleoEducativo(String estaNucleoEducativo) {
		this.estaNucleoEducativo = estaNucleoEducativo;
	}

	@Column(name = "esta_direccion_oficina_nucleo", length = 20)
	public String getEstaDireccionOficinaNucleo() {
		return this.estaDireccionOficinaNucleo;
	}

	public void setEstaDireccionOficinaNucleo(String estaDireccionOficinaNucleo) {
		this.estaDireccionOficinaNucleo = estaDireccionOficinaNucleo;
	}

	@Column(name = "esta_subsidio")
	public Boolean getEstaSubsidio() {
		return this.estaSubsidio;
	}

	public void setEstaSubsidio(Boolean estaSubsidio) {
		this.estaSubsidio = estaSubsidio;
	}

	@Column(name = "esta_capacidades", length = 50)
	public String getEstaCapacidades() {
		return this.estaCapacidades;
	}

	public void setEstaCapacidades(String estaCapacidades) {
		this.estaCapacidades = estaCapacidades;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "establecimiento")
	public Set<Sede> getSedes() {
		return this.sedes;
	}

	public void setSedes(Set<Sede> sedes) {
		this.sedes = sedes;
	}

}
