package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Estrato generated by hbm2java
 */
@Entity
@Table(name = "estrato", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "estrato_nombre"))
public class Estrato implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5757602063976927284L;
	private Integer estratoId;
	private String estratoNombre;
	private Set<Estudiantes> estudianteses = new HashSet<Estudiantes>(0);

	public Estrato() {
	}

	public Estrato(String estratoNombre) {
		this.estratoNombre = estratoNombre;
	}

	public Estrato(String estratoNombre, Set<Estudiantes> estudianteses) {
		this.estratoNombre = estratoNombre;
		this.estudianteses = estudianteses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "estrato_id", unique = true, nullable = false)
	public Integer getEstratoId() {
		return this.estratoId;
	}

	public void setEstratoId(Integer estratoId) {
		this.estratoId = estratoId;
	}

	@Column(name = "estrato_nombre", unique = true, nullable = false, length = 100)
	public String getEstratoNombre() {
		return this.estratoNombre;
	}

	public void setEstratoNombre(String estratoNombre) {
		this.estratoNombre = estratoNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "estrato")
	public Set<Estudiantes> getEstudianteses() {
		return this.estudianteses;
	}

	public void setEstudianteses(Set<Estudiantes> estudianteses) {
		this.estudianteses = estudianteses;
	}

}
