package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Etnias generated by hbm2java
 */
@Entity
@Table(name = "etnias", catalog = "bd_sianglv")
public class Etnias implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1704875015455114917L;
	private Integer etniaId;
	private String etniaNombre;
	private Set<Estudiantes> estudianteses = new HashSet<Estudiantes>(0);

	public Etnias() {
	}

	public Etnias(String etniaNombre) {
		this.etniaNombre = etniaNombre;
	}

	public Etnias(String etniaNombre, Set<Estudiantes> estudianteses) {
		this.etniaNombre = etniaNombre;
		this.estudianteses = estudianteses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "etnia_id", unique = true, nullable = false)
	public Integer getEtniaId() {
		return this.etniaId;
	}

	public void setEtniaId(Integer etniaId) {
		this.etniaId = etniaId;
	}

	@Column(name = "etnia_nombre", nullable = false, length = 50)
	public String getEtniaNombre() {
		return this.etniaNombre;
	}

	public void setEtniaNombre(String etniaNombre) {
		this.etniaNombre = etniaNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "etnias")
	public Set<Estudiantes> getEstudianteses() {
		return this.estudianteses;
	}

	public void setEstudianteses(Set<Estudiantes> estudianteses) {
		this.estudianteses = estudianteses;
	}

}
