package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Experiencia generated by hbm2java
 */
@Entity
@Table(name = "experiencia", catalog = "bd_sianglv")
public class Experiencia implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5196903703398790906L;
	private Integer expId;
	private GradoEscalafon gradoEscalafon;
	private Docentes docentes;
	private String expTiempoSevicio;
	private String expArea;
	private String expInstitucion;

	public Experiencia() {
	}

	public Experiencia(Docentes docentes) {
		this.docentes = docentes;
	}

	public Experiencia(GradoEscalafon gradoEscalafon, Docentes docentes,
			String expTiempoSevicio, String expArea, String expInstitucion) {
		this.gradoEscalafon = gradoEscalafon;
		this.docentes = docentes;
		this.expTiempoSevicio = expTiempoSevicio;
		this.expArea = expArea;
		this.expInstitucion = expInstitucion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "exp_id", unique = true, nullable = false)
	public Integer getExpId() {
		return this.expId;
	}

	public void setExpId(Integer expId) {
		this.expId = expId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gescala_id")
	public GradoEscalafon getGradoEscalafon() {
		return this.gradoEscalafon;
	}

	public void setGradoEscalafon(GradoEscalafon gradoEscalafon) {
		this.gradoEscalafon = gradoEscalafon;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doc_id", nullable = false)
	public Docentes getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Docentes docentes) {
		this.docentes = docentes;
	}

	@Column(name = "exp_tiempo_sevicio", length = 50)
	public String getExpTiempoSevicio() {
		return this.expTiempoSevicio;
	}

	public void setExpTiempoSevicio(String expTiempoSevicio) {
		this.expTiempoSevicio = expTiempoSevicio;
	}

	@Column(name = "exp_area", length = 50)
	public String getExpArea() {
		return this.expArea;
	}

	public void setExpArea(String expArea) {
		this.expArea = expArea;
	}

	@Column(name = "exp_institucion", length = 100)
	public String getExpInstitucion() {
		return this.expInstitucion;
	}

	public void setExpInstitucion(String expInstitucion) {
		this.expInstitucion = expInstitucion;
	}

}
