package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FormacionAcademica generated by hbm2java
 */
@Entity
@Table(name = "formacion_academica", catalog = "bd_sianglv")
public class FormacionAcademica implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2694041988267430553L;
	private Integer foraId;
	private Docentes docentes;
	private String foraNivel;
	private String foraTituloObtenido;
	private String foraInstiucion;

	public FormacionAcademica() {
	}

	public FormacionAcademica(Docentes docentes) {
		this.docentes = docentes;
	}

	public FormacionAcademica(Docentes docentes, String foraNivel,
			String foraTituloObtenido, String foraInstiucion) {
		this.docentes = docentes;
		this.foraNivel = foraNivel;
		this.foraTituloObtenido = foraTituloObtenido;
		this.foraInstiucion = foraInstiucion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "fora_id", unique = true, nullable = false)
	public Integer getForaId() {
		return this.foraId;
	}

	public void setForaId(Integer foraId) {
		this.foraId = foraId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "doc_id", nullable = false)
	public Docentes getDocentes() {
		return this.docentes;
	}

	public void setDocentes(Docentes docentes) {
		this.docentes = docentes;
	}

	@Column(name = "fora_nivel", length = 50)
	public String getForaNivel() {
		return this.foraNivel;
	}

	public void setForaNivel(String foraNivel) {
		this.foraNivel = foraNivel;
	}

	@Column(name = "fora_titulo_obtenido", length = 300)
	public String getForaTituloObtenido() {
		return this.foraTituloObtenido;
	}

	public void setForaTituloObtenido(String foraTituloObtenido) {
		this.foraTituloObtenido = foraTituloObtenido;
	}

	@Column(name = "fora_instiucion", length = 300)
	public String getForaInstiucion() {
		return this.foraInstiucion;
	}

	public void setForaInstiucion(String foraInstiucion) {
		this.foraInstiucion = foraInstiucion;
	}

}
