package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Genero generated by hbm2java
 */
@Entity
@Table(name = "genero", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "genero_nombre"))
public class Genero implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6665243117058112997L;
	private Integer generoId;
	private String generoNombre;
	private boolean generoTipo;
	private Set<Establecimiento> establecimientos = new HashSet<Establecimiento>(
			0);
	private Set<Persona> personas = new HashSet<Persona>(0);

	public Genero() {
	}

	public Genero(String generoNombre, boolean generoTipo) {
		this.generoNombre = generoNombre;
		this.generoTipo = generoTipo;
	}

	public Genero(String generoNombre, boolean generoTipo,
			Set<Establecimiento> establecimientos, Set<Persona> personas) {
		this.generoNombre = generoNombre;
		this.generoTipo = generoTipo;
		this.establecimientos = establecimientos;
		this.personas = personas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "genero_id", unique = true, nullable = false)
	public Integer getGeneroId() {
		return this.generoId;
	}

	public void setGeneroId(Integer generoId) {
		this.generoId = generoId;
	}

	@Column(name = "genero_nombre", unique = true, nullable = false, length = 20)
	public String getGeneroNombre() {
		return this.generoNombre;
	}

	public void setGeneroNombre(String generoNombre) {
		this.generoNombre = generoNombre;
	}

	@Column(name = "genero_tipo", nullable = false)
	public boolean isGeneroTipo() {
		return this.generoTipo;
	}

	public void setGeneroTipo(boolean generoTipo) {
		this.generoTipo = generoTipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genero")
	public Set<Establecimiento> getEstablecimientos() {
		return this.establecimientos;
	}

	public void setEstablecimientos(Set<Establecimiento> establecimientos) {
		this.establecimientos = establecimientos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "genero")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

}
