package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GradoGrupo generated by hbm2java
 */
@Entity
@Table(name = "grado_grupo", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = {
		"gra_id", "gru_id" }))
public class GradoGrupo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3007954877026556762L;
	private Integer ggId;
	private Grupo grupo;
	private Grado grado;
	private Set<UbicacionCurso> ubicacionCursos = new HashSet<UbicacionCurso>(0);

	public GradoGrupo() {
	}

	public GradoGrupo(Grupo grupo, Grado grado) {
		this.grupo = grupo;
		this.grado = grado;
	}

	public GradoGrupo(Grupo grupo, Grado grado,
			Set<UbicacionCurso> ubicacionCursos) {
		this.grupo = grupo;
		this.grado = grado;
		this.ubicacionCursos = ubicacionCursos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "gg_id", unique = true, nullable = false)
	public Integer getGgId() {
		return this.ggId;
	}

	public void setGgId(Integer ggId) {
		this.ggId = ggId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gru_id", nullable = false)
	public Grupo getGrupo() {
		return this.grupo;
	}

	public void setGrupo(Grupo grupo) {
		this.grupo = grupo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gra_id", nullable = false)
	public Grado getGrado() {
		return this.grado;
	}

	public void setGrado(Grado grado) {
		this.grado = grado;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gradoGrupo")
	public Set<UbicacionCurso> getUbicacionCursos() {
		return this.ubicacionCursos;
	}

	public void setUbicacionCursos(Set<UbicacionCurso> ubicacionCursos) {
		this.ubicacionCursos = ubicacionCursos;
	}

}
