package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * GradoMateria generated by hbm2java
 */
@Entity
@Table(name = "grado_materia", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = {
		"gra_id", "mat_id" }))
public class GradoMateria implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9020483812120768180L;
	private Integer gramId;
	private Grado grado;
	private Materias materias;
	private Set<CargaAcademica> cargaAcademicas = new HashSet<CargaAcademica>(0);

	public GradoMateria() {
	}

	public GradoMateria(Grado grado, Materias materias) {
		this.grado = grado;
		this.materias = materias;
	}

	public GradoMateria(Grado grado, Materias materias,
			Set<CargaAcademica> cargaAcademicas) {
		this.grado = grado;
		this.materias = materias;
		this.cargaAcademicas = cargaAcademicas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "gram_id", unique = true, nullable = false)
	public Integer getGramId() {
		return this.gramId;
	}

	public void setGramId(Integer gramId) {
		this.gramId = gramId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gra_id", nullable = false)
	public Grado getGrado() {
		return this.grado;
	}

	public void setGrado(Grado grado) {
		this.grado = grado;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mat_id", nullable = false)
	public Materias getMaterias() {
		return this.materias;
	}

	public void setMaterias(Materias materias) {
		this.materias = materias;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "gradoMateria")
	public Set<CargaAcademica> getCargaAcademicas() {
		return this.cargaAcademicas;
	}

	public void setCargaAcademicas(Set<CargaAcademica> cargaAcademicas) {
		this.cargaAcademicas = cargaAcademicas;
	}

}
