package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Grupo generated by hbm2java
 */
@Entity
@Table(name = "grupo", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "gru_grupo"))
public class Grupo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3324870939312404746L;
	private Integer gruId;
	private String gruGrupo;
	private Set<GradoGrupo> gradoGrupos = new HashSet<GradoGrupo>(0);

	public Grupo() {
	}

	public Grupo(String gruGrupo) {
		this.gruGrupo = gruGrupo;
	}

	public Grupo(String gruGrupo, Set<GradoGrupo> gradoGrupos) {
		this.gruGrupo = gruGrupo;
		this.gradoGrupos = gradoGrupos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "gru_id", unique = true, nullable = false)
	public Integer getGruId() {
		return this.gruId;
	}

	public void setGruId(Integer gruId) {
		this.gruId = gruId;
	}

	@Column(name = "gru_grupo", unique = true, nullable = false, length = 1)
	public String getGruGrupo() {
		return this.gruGrupo;
	}

	public void setGruGrupo(String gruGrupo) {
		this.gruGrupo = gruGrupo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "grupo")
	public Set<GradoGrupo> getGradoGrupos() {
		return this.gradoGrupos;
	}

	public void setGradoGrupos(Set<GradoGrupo> gradoGrupos) {
		this.gradoGrupos = gradoGrupos;
	}

}
