package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Indicadores generated by hbm2java
 */
@Entity
@Table(name = "indicadores", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "ind_codigo"))
public class Indicadores implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5728699714465754392L;
	private Integer indId;
	private Valoracion valoracion;
	private Materias materias;
	private String indCodigo;
	private String indIndicador;
	private Set<PlanillaEvaluacionIndicador> planillaEvaluacionIndicadors = new HashSet<PlanillaEvaluacionIndicador>(
			0);

	public Indicadores() {
	}

	public Indicadores(Valoracion valoracion, Materias materias,
			String indCodigo, String indIndicador) {
		this.valoracion = valoracion;
		this.materias = materias;
		this.indCodigo = indCodigo;
		this.indIndicador = indIndicador;
	}

	public Indicadores(Valoracion valoracion, Materias materias,
			String indCodigo, String indIndicador,
			Set<PlanillaEvaluacionIndicador> planillaEvaluacionIndicadors) {
		this.valoracion = valoracion;
		this.materias = materias;
		this.indCodigo = indCodigo;
		this.indIndicador = indIndicador;
		this.planillaEvaluacionIndicadors = planillaEvaluacionIndicadors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ind_id", unique = true, nullable = false)
	public Integer getIndId() {
		return this.indId;
	}

	public void setIndId(Integer indId) {
		this.indId = indId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "val_id", nullable = false)
	public Valoracion getValoracion() {
		return this.valoracion;
	}

	public void setValoracion(Valoracion valoracion) {
		this.valoracion = valoracion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mat_id", nullable = false)
	public Materias getMaterias() {
		return this.materias;
	}

	public void setMaterias(Materias materias) {
		this.materias = materias;
	}

	@Column(name = "ind_codigo", unique = true, nullable = false, length = 20)
	public String getIndCodigo() {
		return this.indCodigo;
	}

	public void setIndCodigo(String indCodigo) {
		this.indCodigo = indCodigo;
	}

	@Column(name = "ind_indicador", nullable = false)
	public String getIndIndicador() {
		return this.indIndicador;
	}

	public void setIndIndicador(String indIndicador) {
		this.indIndicador = indIndicador;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "indicadores")
	public Set<PlanillaEvaluacionIndicador> getPlanillaEvaluacionIndicadors() {
		return this.planillaEvaluacionIndicadors;
	}

	public void setPlanillaEvaluacionIndicadors(
			Set<PlanillaEvaluacionIndicador> planillaEvaluacionIndicadors) {
		this.planillaEvaluacionIndicadors = planillaEvaluacionIndicadors;
	}

}
