package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Jornada generated by hbm2java
 */
@Entity
@Table(name = "jornada", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "jor_descripcion"))
public class Jornada implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7981576043794419369L;
	private Integer jorId;
	private String jorDescripcion;
	private Set<ConfigSede> configSedes = new HashSet<ConfigSede>(0);

	public Jornada() {
	}

	public Jornada(String jorDescripcion) {
		this.jorDescripcion = jorDescripcion;
	}

	public Jornada(String jorDescripcion, Set<ConfigSede> configSedes) {
		this.jorDescripcion = jorDescripcion;
		this.configSedes = configSedes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "jor_id", unique = true, nullable = false)
	public Integer getJorId() {
		return this.jorId;
	}

	public void setJorId(Integer jorId) {
		this.jorId = jorId;
	}

	@Column(name = "jor_descripcion", unique = true, nullable = false, length = 50)
	public String getJorDescripcion() {
		return this.jorDescripcion;
	}

	public void setJorDescripcion(String jorDescripcion) {
		this.jorDescripcion = jorDescripcion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "jornada")
	public Set<ConfigSede> getConfigSedes() {
		return this.configSedes;
	}

	public void setConfigSedes(Set<ConfigSede> configSedes) {
		this.configSedes = configSedes;
	}

}
