package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Materias generated by hbm2java
 */
@Entity
@Table(name = "materias", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "mat_materia"))
public class Materias implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6225775826102487640L;
	private Integer matId;
	private Area area;
	private String matMateria;
	private int horas;
	private boolean tipo;
	private Set<Indicadores> indicadoreses = new HashSet<Indicadores>(0);
	private Set<GradoMateria> gradoMaterias = new HashSet<GradoMateria>(0);

	public Materias() {
	}

	public Materias(Area area, String matMateria, int horas, boolean tipo) {
		this.area = area;
		this.matMateria = matMateria;
		this.horas = horas;
		this.tipo = tipo;
	}

	public Materias(Area area, String matMateria, int horas, boolean tipo,
			Set<Indicadores> indicadoreses, Set<GradoMateria> gradoMaterias) {
		this.area = area;
		this.matMateria = matMateria;
		this.horas = horas;
		this.tipo = tipo;
		this.indicadoreses = indicadoreses;
		this.gradoMaterias = gradoMaterias;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "mat_id", unique = true, nullable = false)
	public Integer getMatId() {
		return this.matId;
	}

	public void setMatId(Integer matId) {
		this.matId = matId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "are_id", nullable = false)
	public Area getArea() {
		return this.area;
	}

	public void setArea(Area area) {
		this.area = area;
	}

	@Column(name = "mat_materia", unique = true, nullable = false, length = 50)
	public String getMatMateria() {
		return this.matMateria;
	}

	public void setMatMateria(String matMateria) {
		this.matMateria = matMateria;
	}

	@Column(name = "horas", nullable = false)
	public int getHoras() {
		return this.horas;
	}

	public void setHoras(int horas) {
		this.horas = horas;
	}

	@Column(name = "tipo", nullable = false)
	public boolean isTipo() {
		return this.tipo;
	}

	public void setTipo(boolean tipo) {
		this.tipo = tipo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materias")
	public Set<Indicadores> getIndicadoreses() {
		return this.indicadoreses;
	}

	public void setIndicadoreses(Set<Indicadores> indicadoreses) {
		this.indicadoreses = indicadoreses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "materias")
	public Set<GradoMateria> getGradoMaterias() {
		return this.gradoMaterias;
	}

	public void setGradoMaterias(Set<GradoMateria> gradoMaterias) {
		this.gradoMaterias = gradoMaterias;
	}

}
