package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Matricula generated by hbm2java
 */
@Entity
@Table(name = "matricula", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = {
		"res_id", "ubi_id", "ale_id" }))
public class Matricula implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1215107088139870731L;
	private Integer matriId;
	private Estados estadosByMatriCondicionAnterior;
	private AnioLectivo anioLectivo;
	private Acudiente acudiente;
	private UbicacionCurso ubicacionCurso;
	private Estados estadosByMatriSituacionAnterior;
	private Boolean matriSubsidiado;
	private Boolean matriRepitente;
	private Boolean matriNuevo;

	public Matricula() {
	}

	public Matricula(AnioLectivo anioLectivo, Acudiente acudiente,
			UbicacionCurso ubicacionCurso) {
		this.anioLectivo = anioLectivo;
		this.acudiente = acudiente;
		this.ubicacionCurso = ubicacionCurso;
	}

	public Matricula(Estados estadosByMatriCondicionAnterior,
			AnioLectivo anioLectivo, Acudiente acudiente,
			UbicacionCurso ubicacionCurso,
			Estados estadosByMatriSituacionAnterior, Boolean matriSubsidiado,
			Boolean matriRepitente, Boolean matriNuevo) {
		this.estadosByMatriCondicionAnterior = estadosByMatriCondicionAnterior;
		this.anioLectivo = anioLectivo;
		this.acudiente = acudiente;
		this.ubicacionCurso = ubicacionCurso;
		this.estadosByMatriSituacionAnterior = estadosByMatriSituacionAnterior;
		this.matriSubsidiado = matriSubsidiado;
		this.matriRepitente = matriRepitente;
		this.matriNuevo = matriNuevo;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "matri_id", unique = true, nullable = false)
	public Integer getMatriId() {
		return this.matriId;
	}

	public void setMatriId(Integer matriId) {
		this.matriId = matriId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "matri_condicion_anterior")
	public Estados getEstadosByMatriCondicionAnterior() {
		return this.estadosByMatriCondicionAnterior;
	}

	public void setEstadosByMatriCondicionAnterior(
			Estados estadosByMatriCondicionAnterior) {
		this.estadosByMatriCondicionAnterior = estadosByMatriCondicionAnterior;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ale_id", nullable = false)
	public AnioLectivo getAnioLectivo() {
		return this.anioLectivo;
	}

	public void setAnioLectivo(AnioLectivo anioLectivo) {
		this.anioLectivo = anioLectivo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "res_id", nullable = false)
	public Acudiente getAcudiente() {
		return this.acudiente;
	}

	public void setAcudiente(Acudiente acudiente) {
		this.acudiente = acudiente;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ubi_id", nullable = false)
	public UbicacionCurso getUbicacionCurso() {
		return this.ubicacionCurso;
	}

	public void setUbicacionCurso(UbicacionCurso ubicacionCurso) {
		this.ubicacionCurso = ubicacionCurso;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "matri_situacion_anterior")
	public Estados getEstadosByMatriSituacionAnterior() {
		return this.estadosByMatriSituacionAnterior;
	}

	public void setEstadosByMatriSituacionAnterior(
			Estados estadosByMatriSituacionAnterior) {
		this.estadosByMatriSituacionAnterior = estadosByMatriSituacionAnterior;
	}

	@Column(name = "matri_subsidiado")
	public Boolean getMatriSubsidiado() {
		return this.matriSubsidiado;
	}

	public void setMatriSubsidiado(Boolean matriSubsidiado) {
		this.matriSubsidiado = matriSubsidiado;
	}

	@Column(name = "matri_repitente")
	public Boolean getMatriRepitente() {
		return this.matriRepitente;
	}

	public void setMatriRepitente(Boolean matriRepitente) {
		this.matriRepitente = matriRepitente;
	}

	@Column(name = "matri_nuevo")
	public Boolean getMatriNuevo() {
		return this.matriNuevo;
	}

	public void setMatriNuevo(Boolean matriNuevo) {
		this.matriNuevo = matriNuevo;
	}

}
