package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Municipio generated by hbm2java
 */
@Entity
@Table(name = "municipio", catalog = "bd_sianglv")
public class Municipio implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 5906042069335330393L;
	private int munCodigo;
	private Departamento departamento;
	private String munMunicipio;
	private Set<Documento> documentos = new HashSet<Documento>(0);
	private Set<Domicilio> domicilios = new HashSet<Domicilio>(0);
	private Set<Persona> personasForMunIdNac = new HashSet<Persona>(0);
	private Set<Persona> personasForMunIdEmpresa = new HashSet<Persona>(0);
	private Set<Sede> sedes = new HashSet<Sede>(0);
	private Set<Estudiantes> estudianteses = new HashSet<Estudiantes>(0);

	public Municipio() {
	}

	public Municipio(int munCodigo, Departamento departamento,
			String munMunicipio) {
		this.munCodigo = munCodigo;
		this.departamento = departamento;
		this.munMunicipio = munMunicipio;
	}

	public Municipio(int munCodigo, Departamento departamento,
			String munMunicipio, Set<Documento> documentos,
			Set<Domicilio> domicilios, Set<Persona> personasForMunIdNac,
			Set<Persona> personasForMunIdEmpresa, Set<Sede> sedes,
			Set<Estudiantes> estudianteses) {
		this.munCodigo = munCodigo;
		this.departamento = departamento;
		this.munMunicipio = munMunicipio;
		this.documentos = documentos;
		this.domicilios = domicilios;
		this.personasForMunIdNac = personasForMunIdNac;
		this.personasForMunIdEmpresa = personasForMunIdEmpresa;
		this.sedes = sedes;
		this.estudianteses = estudianteses;
	}

	@Id
	@Column(name = "mun_codigo", unique = true, nullable = false)
	public int getMunCodigo() {
		return this.munCodigo;
	}

	public void setMunCodigo(int munCodigo) {
		this.munCodigo = munCodigo;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "dep_codigo", nullable = false)
	public Departamento getDepartamento() {
		return this.departamento;
	}

	public void setDepartamento(Departamento departamento) {
		this.departamento = departamento;
	}

	@Column(name = "mun_municipio", nullable = false, length = 50)
	public String getMunMunicipio() {
		return this.munMunicipio;
	}

	public void setMunMunicipio(String munMunicipio) {
		this.munMunicipio = munMunicipio;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipio")
	public Set<Documento> getDocumentos() {
		return this.documentos;
	}

	public void setDocumentos(Set<Documento> documentos) {
		this.documentos = documentos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipio")
	public Set<Domicilio> getDomicilios() {
		return this.domicilios;
	}

	public void setDomicilios(Set<Domicilio> domicilios) {
		this.domicilios = domicilios;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipioByMunIdNac")
	public Set<Persona> getPersonasForMunIdNac() {
		return this.personasForMunIdNac;
	}

	public void setPersonasForMunIdNac(Set<Persona> personasForMunIdNac) {
		this.personasForMunIdNac = personasForMunIdNac;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipioByMunIdEmpresa")
	public Set<Persona> getPersonasForMunIdEmpresa() {
		return this.personasForMunIdEmpresa;
	}

	public void setPersonasForMunIdEmpresa(Set<Persona> personasForMunIdEmpresa) {
		this.personasForMunIdEmpresa = personasForMunIdEmpresa;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipio")
	public Set<Sede> getSedes() {
		return this.sedes;
	}

	public void setSedes(Set<Sede> sedes) {
		this.sedes = sedes;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "municipio")
	public Set<Estudiantes> getEstudianteses() {
		return this.estudianteses;
	}

	public void setEstudianteses(Set<Estudiantes> estudianteses) {
		this.estudianteses = estudianteses;
	}

}
