package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * NivelEscolaridad generated by hbm2java
 */
@Entity
@Table(name = "nivel_escolaridad", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "nies_nivel"))
public class NivelEscolaridad implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8288647932084337172L;
	private Integer niesId;
	private String niesNivel;
	private Set<ConfigSede> configSedes = new HashSet<ConfigSede>(0);

	public NivelEscolaridad() {
	}

	public NivelEscolaridad(String niesNivel) {
		this.niesNivel = niesNivel;
	}

	public NivelEscolaridad(String niesNivel, Set<ConfigSede> configSedes) {
		this.niesNivel = niesNivel;
		this.configSedes = configSedes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "nies_id", unique = true, nullable = false)
	public Integer getNiesId() {
		return this.niesId;
	}

	public void setNiesId(Integer niesId) {
		this.niesId = niesId;
	}

	@Column(name = "nies_nivel", unique = true, nullable = false, length = 20)
	public String getNiesNivel() {
		return this.niesNivel;
	}

	public void setNiesNivel(String niesNivel) {
		this.niesNivel = niesNivel;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "nivelEscolaridad")
	public Set<ConfigSede> getConfigSedes() {
		return this.configSedes;
	}

	public void setConfigSedes(Set<ConfigSede> configSedes) {
		this.configSedes = configSedes;
	}

}
