package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * NovedadInstitucion generated by hbm2java
 */
@Entity
@Table(name = "novedad_institucion", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "noin_nombre"))
public class NovedadInstitucion implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1381068886814875208L;
	private Integer noinId;
	private String noinNombre;
	private Set<Establecimiento> establecimientos = new HashSet<Establecimiento>(
			0);

	public NovedadInstitucion() {
	}

	public NovedadInstitucion(String noinNombre) {
		this.noinNombre = noinNombre;
	}

	public NovedadInstitucion(String noinNombre,
			Set<Establecimiento> establecimientos) {
		this.noinNombre = noinNombre;
		this.establecimientos = establecimientos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "noin_id", unique = true, nullable = false)
	public Integer getNoinId() {
		return this.noinId;
	}

	public void setNoinId(Integer noinId) {
		this.noinId = noinId;
	}

	@Column(name = "noin_nombre", unique = true, nullable = false, length = 200)
	public String getNoinNombre() {
		return this.noinNombre;
	}

	public void setNoinNombre(String noinNombre) {
		this.noinNombre = noinNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "novedadInstitucion")
	public Set<Establecimiento> getEstablecimientos() {
		return this.establecimientos;
	}

	public void setEstablecimientos(Set<Establecimiento> establecimientos) {
		this.establecimientos = establecimientos;
	}

}
