package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Pais generated by hbm2java
 */
@Entity
@Table(name = "pais", catalog = "bd_sianglv")
public class Pais implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4385792367136730414L;
	private Integer idPais;
	private String nombrePais;
	private Set<Departamento> departamentos = new HashSet<Departamento>(0);

	public Pais() {
	}

	public Pais(String nombrePais) {
		this.nombrePais = nombrePais;
	}

	public Pais(String nombrePais, Set<Departamento> departamentos) {
		this.nombrePais = nombrePais;
		this.departamentos = departamentos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idPais", unique = true, nullable = false)
	public Integer getIdPais() {
		return this.idPais;
	}

	public void setIdPais(Integer idPais) {
		this.idPais = idPais;
	}

	@Column(name = "nombre_pais", nullable = false, length = 45)
	public String getNombrePais() {
		return this.nombrePais;
	}

	public void setNombrePais(String nombrePais) {
		this.nombrePais = nombrePais;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "pais")
	public Set<Departamento> getDepartamentos() {
		return this.departamentos;
	}

	public void setDepartamentos(Set<Departamento> departamentos) {
		this.departamentos = departamentos;
	}

}
