package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Parentesco generated by hbm2java
 */
@Entity
@Table(name = "parentesco", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "parent_nombre"))
public class Parentesco implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1004370982724234350L;
	private Integer parentId;
	private String parentNombre;
	private Set<Acudiente> acudientes = new HashSet<Acudiente>(0);

	public Parentesco() {
	}

	public Parentesco(String parentNombre) {
		this.parentNombre = parentNombre;
	}

	public Parentesco(String parentNombre, Set<Acudiente> acudientes) {
		this.parentNombre = parentNombre;
		this.acudientes = acudientes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "parent_id", unique = true, nullable = false)
	public Integer getParentId() {
		return this.parentId;
	}

	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	@Column(name = "parent_nombre", unique = true, nullable = false, length = 100)
	public String getParentNombre() {
		return this.parentNombre;
	}

	public void setParentNombre(String parentNombre) {
		this.parentNombre = parentNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "parentesco")
	public Set<Acudiente> getAcudientes() {
		return this.acudientes;
	}

	public void setAcudientes(Set<Acudiente> acudientes) {
		this.acudientes = acudientes;
	}

}
