package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * PlanillaEvaluacionIndicador generated by hbm2java
 */
@Entity
@Table(name = "planilla_evaluacion_indicador", catalog = "bd_sianglv")
public class PlanillaEvaluacionIndicador implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -671068683410573619L;
	private Integer plainId;
	private Indicadores indicadores;
	private Planilla planilla;
	private float plainValoracion;

	public PlanillaEvaluacionIndicador() {
	}

	public PlanillaEvaluacionIndicador(Indicadores indicadores,
			Planilla planilla, float plainValoracion) {
		this.indicadores = indicadores;
		this.planilla = planilla;
		this.plainValoracion = plainValoracion;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "plain_id", unique = true, nullable = false)
	public Integer getPlainId() {
		return this.plainId;
	}

	public void setPlainId(Integer plainId) {
		this.plainId = plainId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ind_id", nullable = false)
	public Indicadores getIndicadores() {
		return this.indicadores;
	}

	public void setIndicadores(Indicadores indicadores) {
		this.indicadores = indicadores;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "pla_id", nullable = false)
	public Planilla getPlanilla() {
		return this.planilla;
	}

	public void setPlanilla(Planilla planilla) {
		this.planilla = planilla;
	}

	@Column(name = "plain_valoracion", nullable = false, precision = 9, scale = 3)
	public float getPlainValoracion() {
		return this.plainValoracion;
	}

	public void setPlainValoracion(float plainValoracion) {
		this.plainValoracion = plainValoracion;
	}

}
