package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Planilla generated by hbm2java
 */
@Entity
@Table(name = "planilla", catalog = "bd_sianglv")
public class Planilla implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6863633656261173247L;
	private Integer plaId;
	private CargaAcademica cargaAcademica;
	private Periodo periodo;
	private float plaNotaPromedio;
	private Integer plaFaltas;
	private Float plaHabilitacion;
	private Set<Observaciones> observacioneses = new HashSet<Observaciones>(0);
	private Set<PlanillaEvaluacionIndicador> planillaEvaluacionIndicadors = new HashSet<PlanillaEvaluacionIndicador>(
			0);

	public Planilla() {
	}

	public Planilla(CargaAcademica cargaAcademica, Periodo periodo,
			float plaNotaPromedio) {
		this.cargaAcademica = cargaAcademica;
		this.periodo = periodo;
		this.plaNotaPromedio = plaNotaPromedio;
	}

	public Planilla(CargaAcademica cargaAcademica, Periodo periodo,
			float plaNotaPromedio, Integer plaFaltas, Float plaHabilitacion,
			Set<Observaciones> observacioneses,
			Set<PlanillaEvaluacionIndicador> planillaEvaluacionIndicadors) {
		this.cargaAcademica = cargaAcademica;
		this.periodo = periodo;
		this.plaNotaPromedio = plaNotaPromedio;
		this.plaFaltas = plaFaltas;
		this.plaHabilitacion = plaHabilitacion;
		this.observacioneses = observacioneses;
		this.planillaEvaluacionIndicadors = planillaEvaluacionIndicadors;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "pla_id", unique = true, nullable = false)
	public Integer getPlaId() {
		return this.plaId;
	}

	public void setPlaId(Integer plaId) {
		this.plaId = plaId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "car_id", nullable = false)
	public CargaAcademica getCargaAcademica() {
		return this.cargaAcademica;
	}

	public void setCargaAcademica(CargaAcademica cargaAcademica) {
		this.cargaAcademica = cargaAcademica;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "per_id", nullable = false)
	public Periodo getPeriodo() {
		return this.periodo;
	}

	public void setPeriodo(Periodo periodo) {
		this.periodo = periodo;
	}

	@Column(name = "pla_nota_promedio", nullable = false, precision = 9, scale = 3)
	public float getPlaNotaPromedio() {
		return this.plaNotaPromedio;
	}

	public void setPlaNotaPromedio(float plaNotaPromedio) {
		this.plaNotaPromedio = plaNotaPromedio;
	}

	@Column(name = "pla_faltas")
	public Integer getPlaFaltas() {
		return this.plaFaltas;
	}

	public void setPlaFaltas(Integer plaFaltas) {
		this.plaFaltas = plaFaltas;
	}

	@Column(name = "pla_habilitacion", precision = 9, scale = 3)
	public Float getPlaHabilitacion() {
		return this.plaHabilitacion;
	}

	public void setPlaHabilitacion(Float plaHabilitacion) {
		this.plaHabilitacion = plaHabilitacion;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planilla")
	public Set<Observaciones> getObservacioneses() {
		return this.observacioneses;
	}

	public void setObservacioneses(Set<Observaciones> observacioneses) {
		this.observacioneses = observacioneses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "planilla")
	public Set<PlanillaEvaluacionIndicador> getPlanillaEvaluacionIndicadors() {
		return this.planillaEvaluacionIndicadors;
	}

	public void setPlanillaEvaluacionIndicadors(
			Set<PlanillaEvaluacionIndicador> planillaEvaluacionIndicadors) {
		this.planillaEvaluacionIndicadors = planillaEvaluacionIndicadors;
	}

}
