package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * PropiedadJuridica generated by hbm2java
 */
@Entity
@Table(name = "propiedad_juridica", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "proju_nombre"))
public class PropiedadJuridica implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3174753647411370358L;
	private Integer projuId;
	private String projuNombre;
	private Set<Establecimiento> establecimientos = new HashSet<Establecimiento>(
			0);

	public PropiedadJuridica() {
	}

	public PropiedadJuridica(String projuNombre) {
		this.projuNombre = projuNombre;
	}

	public PropiedadJuridica(String projuNombre,
			Set<Establecimiento> establecimientos) {
		this.projuNombre = projuNombre;
		this.establecimientos = establecimientos;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "proju_id", unique = true, nullable = false)
	public Integer getProjuId() {
		return this.projuId;
	}

	public void setProjuId(Integer projuId) {
		this.projuId = projuId;
	}

	@Column(name = "proju_nombre", unique = true, nullable = false, length = 100)
	public String getProjuNombre() {
		return this.projuNombre;
	}

	public void setProjuNombre(String projuNombre) {
		this.projuNombre = projuNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "propiedadJuridica")
	public Set<Establecimiento> getEstablecimientos() {
		return this.establecimientos;
	}

	public void setEstablecimientos(Set<Establecimiento> establecimientos) {
		this.establecimientos = establecimientos;
	}

}
