package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Resguardo generated by hbm2java
 */
@Entity
@Table(name = "resguardo", catalog = "bd_sianglv")
public class Resguardo implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2364356721899233328L;
	private Integer resguardoId;
	private String resguardoNombre;
	private Set<Estudiantes> estudianteses = new HashSet<Estudiantes>(0);

	public Resguardo() {
	}

	public Resguardo(String resguardoNombre) {
		this.resguardoNombre = resguardoNombre;
	}

	public Resguardo(String resguardoNombre, Set<Estudiantes> estudianteses) {
		this.resguardoNombre = resguardoNombre;
		this.estudianteses = estudianteses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "resguardo_id", unique = true, nullable = false)
	public Integer getResguardoId() {
		return this.resguardoId;
	}

	public void setResguardoId(Integer resguardoId) {
		this.resguardoId = resguardoId;
	}

	@Column(name = "resguardo_nombre", nullable = false, length = 50)
	public String getResguardoNombre() {
		return this.resguardoNombre;
	}

	public void setResguardoNombre(String resguardoNombre) {
		this.resguardoNombre = resguardoNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "resguardo")
	public Set<Estudiantes> getEstudianteses() {
		return this.estudianteses;
	}

	public void setEstudianteses(Set<Estudiantes> estudianteses) {
		this.estudianteses = estudianteses;
	}

}
