package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Sector generated by hbm2java
 */
@Entity
@Table(name = "sector", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "sector_nombre"))
public class Sector implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4137838027515523827L;
	private Integer sectorId;
	private String sectorNombre;
	private Set<Sede> sedes = new HashSet<Sede>(0);

	public Sector() {
	}

	public Sector(String sectorNombre) {
		this.sectorNombre = sectorNombre;
	}

	public Sector(String sectorNombre, Set<Sede> sedes) {
		this.sectorNombre = sectorNombre;
		this.sedes = sedes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sector_id", unique = true, nullable = false)
	public Integer getSectorId() {
		return this.sectorId;
	}

	public void setSectorId(Integer sectorId) {
		this.sectorId = sectorId;
	}

	@Column(name = "sector_nombre", unique = true, nullable = false, length = 50)
	public String getSectorNombre() {
		return this.sectorNombre;
	}

	public void setSectorNombre(String sectorNombre) {
		this.sectorNombre = sectorNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sector")
	public Set<Sede> getSedes() {
		return this.sedes;
	}

	public void setSedes(Set<Sede> sedes) {
		this.sedes = sedes;
	}

}
