package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Sede generated by hbm2java
 */
@Entity
@Table(name = "sede", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "sed_nombre"))
public class Sede implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2825854232521036735L;
	private Integer sedId;
	private Zona zona;
	private Municipio municipio;
	private Establecimiento establecimiento;
	private Sector sector;
	private String sedDane;
	private String sedNombre;
	private String sedBarrio;
	private String sedDireccion;
	private Boolean sedEtnia;
	private String sedResguardo;
	private boolean sedPrincipal;
	private Set<ConfigSede> configSedes = new HashSet<ConfigSede>(0);

	public Sede() {
	}

	public Sede(Municipio municipio, Establecimiento establecimiento,
			String sedDane, String sedNombre, String sedDireccion,
			boolean sedPrincipal) {
		this.municipio = municipio;
		this.establecimiento = establecimiento;
		this.sedDane = sedDane;
		this.sedNombre = sedNombre;
		this.sedDireccion = sedDireccion;
		this.sedPrincipal = sedPrincipal;
	}

	public Sede(Zona zona, Municipio municipio,
			Establecimiento establecimiento, Sector sector, String sedDane,
			String sedNombre, String sedBarrio, String sedDireccion,
			Boolean sedEtnia, String sedResguardo, boolean sedPrincipal,
			Set<ConfigSede> configSedes) {
		this.zona = zona;
		this.municipio = municipio;
		this.establecimiento = establecimiento;
		this.sector = sector;
		this.sedDane = sedDane;
		this.sedNombre = sedNombre;
		this.sedBarrio = sedBarrio;
		this.sedDireccion = sedDireccion;
		this.sedEtnia = sedEtnia;
		this.sedResguardo = sedResguardo;
		this.sedPrincipal = sedPrincipal;
		this.configSedes = configSedes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "sed_id", unique = true, nullable = false)
	public Integer getSedId() {
		return this.sedId;
	}

	public void setSedId(Integer sedId) {
		this.sedId = sedId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "zona_id")
	public Zona getZona() {
		return this.zona;
	}

	public void setZona(Zona zona) {
		this.zona = zona;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "mun_id", nullable = false)
	public Municipio getMunicipio() {
		return this.municipio;
	}

	public void setMunicipio(Municipio municipio) {
		this.municipio = municipio;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "esta_id", nullable = false)
	public Establecimiento getEstablecimiento() {
		return this.establecimiento;
	}

	public void setEstablecimiento(Establecimiento establecimiento) {
		this.establecimiento = establecimiento;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "sector_id")
	public Sector getSector() {
		return this.sector;
	}

	public void setSector(Sector sector) {
		this.sector = sector;
	}

	@Column(name = "sed_dane", nullable = false, length = 20)
	public String getSedDane() {
		return this.sedDane;
	}

	public void setSedDane(String sedDane) {
		this.sedDane = sedDane;
	}

	@Column(name = "sed_nombre", unique = true, nullable = false, length = 50)
	public String getSedNombre() {
		return this.sedNombre;
	}

	public void setSedNombre(String sedNombre) {
		this.sedNombre = sedNombre;
	}

	@Column(name = "sed_barrio", length = 50)
	public String getSedBarrio() {
		return this.sedBarrio;
	}

	public void setSedBarrio(String sedBarrio) {
		this.sedBarrio = sedBarrio;
	}

	@Column(name = "sed_direccion", nullable = false, length = 50)
	public String getSedDireccion() {
		return this.sedDireccion;
	}

	public void setSedDireccion(String sedDireccion) {
		this.sedDireccion = sedDireccion;
	}

	@Column(name = "sed_etnia")
	public Boolean getSedEtnia() {
		return this.sedEtnia;
	}

	public void setSedEtnia(Boolean sedEtnia) {
		this.sedEtnia = sedEtnia;
	}

	@Column(name = "sed_resguardo", length = 20)
	public String getSedResguardo() {
		return this.sedResguardo;
	}

	public void setSedResguardo(String sedResguardo) {
		this.sedResguardo = sedResguardo;
	}

	@Column(name = "sed_principal", nullable = false)
	public boolean isSedPrincipal() {
		return this.sedPrincipal;
	}

	public void setSedPrincipal(boolean sedPrincipal) {
		this.sedPrincipal = sedPrincipal;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "sede")
	public Set<ConfigSede> getConfigSedes() {
		return this.configSedes;
	}

	public void setConfigSedes(Set<ConfigSede> configSedes) {
		this.configSedes = configSedes;
	}

}
