package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TipoSangre generated by hbm2java
 */
@Entity
@Table(name = "tipo_sangre", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "tsangre_nombre"))
public class TipoSangre implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -9085395077374978770L;
	private Integer tsangreId;
	private String tsangreNombre;
	private Set<Estudiantes> estudianteses = new HashSet<Estudiantes>(0);

	public TipoSangre() {
	}

	public TipoSangre(String tsangreNombre) {
		this.tsangreNombre = tsangreNombre;
	}

	public TipoSangre(String tsangreNombre, Set<Estudiantes> estudianteses) {
		this.tsangreNombre = tsangreNombre;
		this.estudianteses = estudianteses;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tsangre_id", unique = true, nullable = false)
	public Integer getTsangreId() {
		return this.tsangreId;
	}

	public void setTsangreId(Integer tsangreId) {
		this.tsangreId = tsangreId;
	}

	@Column(name = "tsangre_nombre", unique = true, nullable = false, length = 50)
	public String getTsangreNombre() {
		return this.tsangreNombre;
	}

	public void setTsangreNombre(String tsangreNombre) {
		this.tsangreNombre = tsangreNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoSangre")
	public Set<Estudiantes> getEstudianteses() {
		return this.estudianteses;
	}

	public void setEstudianteses(Set<Estudiantes> estudianteses) {
		this.estudianteses = estudianteses;
	}

}
