package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * TipoPersona generated by hbm2java
 */
@Entity
@Table(name = "tipo_persona", catalog = "bd_sianglv")
public class TipoPersona implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 8899222545697482585L;
	private Integer tipoId;
	private String tipoNombre;
	private Set<Persona> personas = new HashSet<Persona>(0);

	public TipoPersona() {
	}

	public TipoPersona(String tipoNombre) {
		this.tipoNombre = tipoNombre;
	}

	public TipoPersona(String tipoNombre, Set<Persona> personas) {
		this.tipoNombre = tipoNombre;
		this.personas = personas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "tipo_id", unique = true, nullable = false)
	public Integer getTipoId() {
		return this.tipoId;
	}

	public void setTipoId(Integer tipoId) {
		this.tipoId = tipoId;
	}

	@Column(name = "tipo_nombre", nullable = false, length = 50)
	public String getTipoNombre() {
		return this.tipoNombre;
	}

	public void setTipoNombre(String tipoNombre) {
		this.tipoNombre = tipoNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "tipoPersona")
	public Set<Persona> getPersonas() {
		return this.personas;
	}

	public void setPersonas(Set<Persona> personas) {
		this.personas = personas;
	}

}
