package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * UbicacionCurso generated by hbm2java
 */
@Entity
@Table(name = "ubicacion_curso", catalog = "bd_sianglv")
public class UbicacionCurso implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4598764195978696912L;
	private Integer ubiId;
	private ConfigSede configSede;
	private GradoGrupo gradoGrupo;
	private Set<CargaAcademica> cargaAcademicas = new HashSet<CargaAcademica>(0);
	private Set<DirectorGrupo> directorGrupos = new HashSet<DirectorGrupo>(0);
	private Set<Matricula> matriculas = new HashSet<Matricula>(0);

	public UbicacionCurso() {
	}

	public UbicacionCurso(ConfigSede configSede, GradoGrupo gradoGrupo) {
		this.configSede = configSede;
		this.gradoGrupo = gradoGrupo;
	}

	public UbicacionCurso(ConfigSede configSede, GradoGrupo gradoGrupo,
			Set<CargaAcademica> cargaAcademicas,
			Set<DirectorGrupo> directorGrupos, Set<Matricula> matriculas) {
		this.configSede = configSede;
		this.gradoGrupo = gradoGrupo;
		this.cargaAcademicas = cargaAcademicas;
		this.directorGrupos = directorGrupos;
		this.matriculas = matriculas;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "ubi_id", unique = true, nullable = false)
	public Integer getUbiId() {
		return this.ubiId;
	}

	public void setUbiId(Integer ubiId) {
		this.ubiId = ubiId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "conf_id", nullable = false)
	public ConfigSede getConfigSede() {
		return this.configSede;
	}

	public void setConfigSede(ConfigSede configSede) {
		this.configSede = configSede;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "gg_id", nullable = false)
	public GradoGrupo getGradoGrupo() {
		return this.gradoGrupo;
	}

	public void setGradoGrupo(GradoGrupo gradoGrupo) {
		this.gradoGrupo = gradoGrupo;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ubicacionCurso")
	public Set<CargaAcademica> getCargaAcademicas() {
		return this.cargaAcademicas;
	}

	public void setCargaAcademicas(Set<CargaAcademica> cargaAcademicas) {
		this.cargaAcademicas = cargaAcademicas;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ubicacionCurso")
	public Set<DirectorGrupo> getDirectorGrupos() {
		return this.directorGrupos;
	}

	public void setDirectorGrupos(Set<DirectorGrupo> directorGrupos) {
		this.directorGrupos = directorGrupos;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "ubicacionCurso")
	public Set<Matricula> getMatriculas() {
		return this.matriculas;
	}

	public void setMatriculas(Set<Matricula> matriculas) {
		this.matriculas = matriculas;
	}

}
