package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Usuarios generated by hbm2java
 */
@Entity
@Table(name = "usuarios", catalog = "bd_sianglv", uniqueConstraints = {
		@UniqueConstraint(columnNames = "password"),
		@UniqueConstraint(columnNames = "login") })
public class Usuarios implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -8076550297807039665L;
	private Integer usId;
	private Roles roles;
	private Persona persona;
	private String login;
	private String password;
	private boolean usEstado;

	public Usuarios() {
	}

	public Usuarios(Roles roles, Persona persona, String login,
			String password, boolean usEstado) {
		this.roles = roles;
		this.persona = persona;
		this.login = login;
		this.password = password;
		this.usEstado = usEstado;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "us_id", unique = true, nullable = false)
	public Integer getUsId() {
		return this.usId;
	}

	public void setUsId(Integer usId) {
		this.usId = usId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "rol_id", nullable = false)
	public Roles getRoles() {
		return this.roles;
	}

	public void setRoles(Roles roles) {
		this.roles = roles;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "per_id", nullable = false)
	public Persona getPersona() {
		return this.persona;
	}

	public void setPersona(Persona persona) {
		this.persona = persona;
	}

	@Column(name = "login", unique = true, nullable = false, length = 20)
	public String getLogin() {
		return this.login;
	}

	public void setLogin(String login) {
		this.login = login;
	}

	@Column(name = "password", unique = true, nullable = false, length = 20)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "us_estado", nullable = false)
	public boolean isUsEstado() {
		return this.usEstado;
	}

	public void setUsEstado(boolean usEstado) {
		this.usEstado = usEstado;
	}

}
