package com.david.sirene.EntidadesxHibernate;

// Generated 15/01/2014 11:40:41 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Zona generated by hbm2java
 */
@Entity
@Table(name = "zona", catalog = "bd_sianglv", uniqueConstraints = @UniqueConstraint(columnNames = "zona_nombre"))
public class Zona implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 3422586802525030964L;
	private Integer zonaId;
	private String zonaNombre;
	private Set<Estudiantes> estudianteses = new HashSet<Estudiantes>(0);
	private Set<Sede> sedes = new HashSet<Sede>(0);

	public Zona() {
	}

	public Zona(String zonaNombre) {
		this.zonaNombre = zonaNombre;
	}

	public Zona(String zonaNombre, Set<Estudiantes> estudianteses,
			Set<Sede> sedes) {
		this.zonaNombre = zonaNombre;
		this.estudianteses = estudianteses;
		this.sedes = sedes;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "zona_id", unique = true, nullable = false)
	public Integer getZonaId() {
		return this.zonaId;
	}

	public void setZonaId(Integer zonaId) {
		this.zonaId = zonaId;
	}

	@Column(name = "zona_nombre", unique = true, nullable = false, length = 100)
	public String getZonaNombre() {
		return this.zonaNombre;
	}

	public void setZonaNombre(String zonaNombre) {
		this.zonaNombre = zonaNombre;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zona")
	public Set<Estudiantes> getEstudianteses() {
		return this.estudianteses;
	}

	public void setEstudianteses(Set<Estudiantes> estudianteses) {
		this.estudianteses = estudianteses;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "zona")
	public Set<Sede> getSedes() {
		return this.sedes;
	}

	public void setSedes(Set<Sede> sedes) {
		this.sedes = sedes;
	}

}
